export const styles = {
  root: {
    fontFamily: "Arial, Tahoma, 'Segoe UI', sans-serif",
    background: "#f6f6f6",
    minHeight: "100vh",
    color: "#1f2937",
    display: "flex",
    flexDirection: "column",
  },
  appShell: {
    width: "100%",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#f6f6f6",
  },

  // Header kiểu báo/cổng thông tin: nền trắng, đỏ chủ đạo, nav ngang không icon
  header: {
    position: "sticky",
    top: 0,
    zIndex: 80,
    width: "100%",
    background: "#fff",
    borderBottom: "1px solid #e5e7eb",
    boxSizing: "border-box",
    boxShadow: "0 1px 0 rgba(0,0,0,0.04)",
  },
  headerTopLine: {
    width: "100%",
    height: 4,
    background: "#b91c1c",
  },
  govMasthead: {
    width: "100%",
    background: "#fff",
    backgroundImage: "radial-gradient(circle at 65% 20%, rgba(185,28,28,0.06) 0, rgba(185,28,28,0.06) 2px, transparent 2px)",
    backgroundSize: "12px 12px",
    borderBottom: "1px solid #f1f1f1",
  },
  govMastheadInner: {
    width: "100%",
    maxWidth: 1200,
    minHeight: 128,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 26,
    padding: "22px 32px 18px",
    boxSizing: "border-box",
  },
  govLogoImage: {
    width: 104,
    height: 104,
    objectFit: "contain",
    flexShrink: 0,
  },
  govTitleBlock: {
    textAlign: "center",
    minWidth: 0,
  },
  govKicker: {
    fontSize: 15,
    fontWeight: 850,
    color: "#1f2937",
    letterSpacing: "normal",
    marginBottom: 6,
  },
  govMainTitle: {
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: 44,
    lineHeight: 1.05,
    fontWeight: 800,
    color: "#dc2626",
    letterSpacing: "normal",
  },
  govMeta: {
    marginTop: 8,
    fontSize: 13,
    color: "#4b5563",
    fontWeight: 700,
  },
  navbarWrap: {
    width: "100%",
    background: "#fff",
    borderTop: "1px solid #f3f4f6",
    borderBottom: "1px solid #e5e7eb",
  },
  topNav: {
    width: "100%",
    maxWidth: 1200,
    minHeight: 58,
    margin: "0 auto",
    padding: "0 32px",
    display: "flex",
    alignItems: "stretch",
    gap: 0,
    boxSizing: "border-box",
    overflowX: "auto",
  },
  topNavBtn: {
    border: "none",
    borderBottom: "3px solid transparent",
    background: "transparent",
    color: "#111827",
    padding: "0 20px",
    minHeight: 58,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    textTransform: "none",
    letterSpacing: "normal",
    fontFamily: "inherit",
    whiteSpace: "nowrap",
  },
  topNavBtnActive: {
    color: "#dc2626",
    borderBottom: "3px solid #dc2626",
    background: "#fff",
  },

  main: {
    flex: 1,
    width: "100%",
    minWidth: 0,
    padding: "26px 28px 34px",
    boxSizing: "border-box",
  },
  page: { width: "100%", maxWidth: 1200, margin: "0 auto" },

  footer: {
    width: "100%",
    background: "#fff",
    borderTop: "4px solid #b91c1c",
    color: "#4b5563",
    boxSizing: "border-box",
  },
  footerInner: {
    width: "100%",
    maxWidth: 1200,
    minHeight: 58,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "14px 32px",
    boxSizing: "border-box",
    flexWrap: "wrap",
    fontSize: 12,
  },

  hero: {
    position: "relative",
    minHeight: 330,
    background: "linear-gradient(90deg, rgba(127,29,29,0.92), rgba(185,28,28,0.78)), var(--home-cover-image, none)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#fff",
    borderRadius: 0,
    padding: "48px 52px",
    boxShadow: "0 10px 26px rgba(127, 29, 29, 0.16)",
    overflow: "hidden",
    border: "1px solid rgba(185,28,28,0.18)",
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.14)",
    border: "1px solid rgba(255,255,255,0.22)",
    padding: "6px 11px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 850,
    marginBottom: 16,
  },
  heroTitle: { fontSize: 36, lineHeight: 1.16, margin: "0 0 12px", letterSpacing: "-0.7px", maxWidth: 860 },
  heroDesc: { fontSize: 15, lineHeight: 1.8, color: "#fee2e2", maxWidth: 860, margin: 0 },
  heroActions: { marginTop: 24, display: "flex", gap: 10, flexWrap: "wrap" },
  primaryBtn: { border: "none", background: "#fff", color: "#b91c1c", borderRadius: 4, padding: "12px 18px", fontSize: 14, fontWeight: 900, cursor: "pointer" },
  secondaryBtn: { border: "1px solid rgba(255,255,255,0.45)", background: "rgba(255,255,255,0.1)", color: "#fff", borderRadius: 4, padding: "12px 18px", fontSize: 14, fontWeight: 900, cursor: "pointer" },

  grid3: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 16, marginTop: 18 },
  grid2: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 16 },
  card: { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: 20, boxShadow: "0 2px 10px rgba(0, 0, 0, 0.035)" },
  cardTitle: { margin: "0 0 8px", fontSize: 16, fontWeight: 850, color: "#991b1b" },
  cardText: { margin: 0, color: "#4b5563", lineHeight: 1.7, fontSize: 14 },
  pageTitle: { margin: "0 0 8px", fontSize: 28, fontWeight: 900, letterSpacing: "-0.5px", color: "#991b1b" },
  pageDesc: { margin: "0 0 20px", color: "#4b5563", lineHeight: 1.7, fontSize: 14, maxWidth: 860 },
  section: { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: 22, marginBottom: 16, boxShadow: "0 2px 10px rgba(0, 0, 0, 0.035)" },
  sectionHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14, fontSize: 16, fontWeight: 850, color: "#991b1b" },

  uploadZone: { border: "2px dashed", borderRadius: 2, padding: "46px 32px", textAlign: "center", transition: "all .18s", background: "#fafafa" },
  modelBox: { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: 18, marginBottom: 16 },
  modelSelect: { width: "100%", padding: "10px 12px", border: "1px solid #d1d5db", borderRadius: 2, background: "#fff", color: "#111827", fontSize: 14, outline: "none" },
  muted: { color: "#6b7280", fontSize: 12 },
  errorBox: { marginTop: 16, background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 2, padding: "12px 16px", color: "#dc2626", fontSize: 14, display: "flex", gap: 8, alignItems: "center" },
  loadingBox: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12, padding: "90px 0" },
  spinner: { width: 44, height: 44, border: "4px solid #e5e7eb", borderTopColor: "#dc2626", borderRadius: "50%", animation: "spin .8s linear infinite" },

  fileBar: { display: "flex", alignItems: "center", gap: 10, background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: "12px 18px", marginBottom: 16, flexWrap: "wrap" },
  totalBadge: { marginLeft: "auto", background: "#991b1b", color: "#fff", borderRadius: 999, padding: "4px 12px", fontSize: 13, fontWeight: 800 },
  tabs: { display: "flex", gap: 6, background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: 6, marginBottom: 16 },
  tab: { flex: 1, padding: "10px 8px", border: "none", borderRadius: 2, background: "transparent", color: "#4b5563", fontSize: 13, fontWeight: 800, cursor: "pointer" },
  tabActive: { background: "#b91c1c", color: "#fff" },

  pdfPanelRoot: { display: "flex", gap: 16, height: "calc(100vh - 318px)", minHeight: 460 },
  pdfViewerCol: { flex: "0 0 50%", display: "flex", flexDirection: "column", background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, overflow: "hidden" },
  pdfTextCol: { flex: 1, display: "flex", flexDirection: "column", background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, overflow: "hidden" },
  pdfPanelHeader: { padding: "12px 16px", fontWeight: 850, fontSize: 13, color: "#991b1b", background: "#f9fafb", borderBottom: "1px solid #e5e7eb", display: "flex", alignItems: "center", gap: 8 },
  pdfIframe: { flex: 1, width: "100%", border: "none" },
  pdfTextScroll: { flex: 1, overflowY: "auto", padding: "16px 20px" },
  pdfSectionTitle: { fontSize: 14, fontWeight: 850, color: "#991b1b", margin: "0 0 10px", display: "flex", alignItems: "center", gap: 8 },
  entityCountBadge: { fontSize: 11, fontWeight: 500, color: "#6b7280", background: "#f3f4f6", borderRadius: 999, padding: "2px 8px", marginLeft: "auto" },
  textBox: { background: "#fafafa", borderRadius: 2, padding: "14px 16px", border: "1px solid #f1f5f9" },
  rawText: { lineHeight: 1.9, fontSize: 14, color: "#374151", margin: 0, whiteSpace: "pre-wrap", wordBreak: "break-word" },
  legend: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 10 },
  legendItem: { fontSize: 11, fontWeight: 750, background: "#f9fafb", borderRadius: 999, padding: "3px 8px", border: "1px solid #e5e7eb" },

  infoGrid: { display: "flex", flexDirection: "column", gap: 10 },
  infoRow: { display: "flex", alignItems: "flex-start", gap: 16, padding: "9px 0", borderBottom: "1px solid #f8fafc" },
  infoLabel: { width: 150, color: "#6b7280", fontSize: 13, fontWeight: 800, flexShrink: 0 },
  infoValue: { flex: 1 },
  chipWrap: { display: "flex", flexWrap: "wrap", gap: 6 },
  chip: { display: "inline-flex", alignItems: "center", gap: 6, borderRadius: 999, padding: "5px 10px", fontSize: 13, fontWeight: 750, border: "1px solid transparent" },
  entityGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 16 },
  entityCard: { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, overflow: "hidden" },
  entityCardHeader: { display: "flex", alignItems: "center", gap: 8, padding: "12px 14px", background: "#fafafa" },

  resourceCard: { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 2, padding: 18, display: "flex", flexDirection: "column", gap: 8, minHeight: 170 },
  resourceLink: { color: "#b91c1c", fontWeight: 850, textDecoration: "none", fontSize: 14 },
  tag: { display: "inline-flex", alignItems: "center", borderRadius: 999, background: "#f3f4f6", color: "#4b5563", padding: "3px 8px", fontSize: 11, fontWeight: 800 },
  guidelineCard: { border: "1px solid #e5e7eb", borderRadius: 2, padding: 16, background: "#fff" },
  guidelineGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(310px, 1fr))", gap: 14 },
  list: { margin: "10px 0 0 18px", padding: 0, color: "#4b5563", lineHeight: 1.7, fontSize: 13 },
  emptyState: { textAlign: "center", color: "#9ca3af", fontSize: 14, padding: 48 },
  resetBtn: { border: "1px solid #d1d5db", background: "#fff", color: "#374151", borderRadius: 2, padding: "8px 12px", fontSize: 13, fontWeight: 850, cursor: "pointer" },


  // Trang chủ gọn, ít chữ, phong cách cổng thông tin
  homeHeroClean: {
    minHeight: 300,
    background: "linear-gradient(90deg, rgba(153,27,27,0.94), rgba(185,28,28,0.76)), var(--home-cover-image, none)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    border: "1px solid #e5e7eb",
    borderTop: "4px solid #b91c1c",
    padding: "44px 48px",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
  },
  homeHeroContent: {
    maxWidth: 760,
  },
  homeEyebrow: {
    fontSize: 13,
    fontWeight: 800,
    color: "#fee2e2",
    marginBottom: 10,
    letterSpacing: "normal",
  },
  homeTitle: {
    margin: "0 0 12px",
    fontSize: 34,
    lineHeight: 1.18,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "normal",
  },
  homeLead: {
    margin: 0,
    maxWidth: 680,
    fontSize: 15,
    lineHeight: 1.7,
    color: "#fee2e2",
  },
  secondaryBtnLight: {
    border: "1px solid rgba(255,255,255,0.55)",
    background: "transparent",
    color: "#fff",
    borderRadius: 2,
    padding: "12px 18px",
    fontSize: 14,
    fontWeight: 850,
    cursor: "pointer",
  },
  homeQuickPanel: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 0,
    marginTop: 16,
    background: "#fff",
    border: "1px solid #e5e7eb",
  },
  homeQuickItem: {
    padding: "18px 20px",
    borderRight: "1px solid #e5e7eb",
  },
  homeQuickLabel: {
    display: "block",
    color: "#b91c1c",
    fontSize: 12,
    fontWeight: 850,
    marginBottom: 6,
  },
  homeBottomGrid: {
    display: "grid",
    gridTemplateColumns: "1.2fr .8fr",
    gap: 16,
    marginTop: 16,
  },
  homePlainCard: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    padding: 20,
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.035)",
  },

  homeQuickTitle: {
    display: "block",
    color: "#111827",
    fontSize: 15,
    fontWeight: 850,
  },
  homeQuickText: {
    margin: "6px 0 0",
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 1.55,
  },
  homeCardTitle: {
    margin: "0 0 10px",
    color: "#991b1b",
    fontSize: 17,
    fontWeight: 850,
  },
  homeCardText: {
    margin: 0,
    color: "#4b5563",
    fontSize: 14,
    lineHeight: 1.65,
  },
  labelListCompact: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  labelPillPlain: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 13,
    fontWeight: 800,
    border: "1px solid transparent",
  },
  linkLikeBtn: {
    marginTop: 12,
    border: "none",
    background: "transparent",
    color: "#b91c1c",
    fontSize: 14,
    fontWeight: 850,
    cursor: "pointer",
    padding: 0,
  },
  mobileHint: { display: "none" },
};
